DROP TABLE IF EXISTS `RETRIEVAL`.`T_ATTRIBUTE`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_CUSTOMER_FIELD`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_IMAGE`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_MATRIX`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_MATRIX_ROW`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_NODE`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_RETRIEVAL_DATA_SOURCE`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_RETRIEVAL_DATA_SOURCE_CHILDS`;
DROP TABLE IF EXISTS `RETRIEVAL`.`T_USER`;

CREATE TABLE `T_ATTRIBUTE` (
  `ID` VARCHAR(40) NOT NULL,
  `ATTR_NAME` VARCHAR(45) DEFAULT NULL,
  `ATTR_NAME_EN` VARCHAR(45) DEFAULT NULL,
  `ATTR_HEADER_ID` VARCHAR(40) DEFAULT NULL,
  `ATTR_DESC` VARCHAR(100) DEFAULT NULL,
  `ATTR_INDEX` INT(11) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_CUSTOMER_FIELD` (
  `ID` VARCHAR(40) NOT NULL,
  `FD_KEY` VARCHAR(40) DEFAULT NULL,
  `FD_VALUE` VARCHAR(40) DEFAULT NULL,
  `FD_HEADER_ID` VARCHAR(40) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_IMAGE` (
  `ID` VARCHAR(40) NOT NULL,
  `IMG_PATH` VARCHAR(50) DEFAULT NULL,
  `IMG_HEADER_ID` VARCHAR(40) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_MATRIX` (
  `ID` VARCHAR(40) NOT NULL,
  `MTX_HEADER_ID` VARCHAR(40) NOT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_MATRIX_ROW` (
  `ID` VARCHAR(40) NOT NULL,
  `MTXR_MATRIX_ID` VARCHAR(40) NOT NULL,
  `MTXR_ROW_INDEX` INT(11) NOT NULL,
  `MTXR_COL_INDEX` INT(11) NOT NULL,
  `MTXR_VALUE` INT(11) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_NODE` (
  `ID` VARCHAR(40) NOT NULL,
  `ND_NAME` VARCHAR(45) DEFAULT NULL,
  `ND_NAME_EN` VARCHAR(45) DEFAULT NULL,
  `ND_URI` VARCHAR(45) DEFAULT NULL,
  `ND_URI_NAME` VARCHAR(45) DEFAULT NULL,
  `ND_PARENT_ID` VARCHAR(45) DEFAULT NULL,
  `ND_DETAIL_TYPE_ID` VARCHAR(40) DEFAULT NULL,
  `ND_CONTACT` VARCHAR(100) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_RETRIEVAL_DATA_SOURCE` (
  `ID` VARCHAR(40) NOT NULL,
  `RDS_HEADER_ID` VARCHAR(40) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_RETRIEVAL_DATA_SOURCE_CHILDS` (
  `ID` VARCHAR(40) NOT NULL,
  `RDSC_HEADER_ID` VARCHAR(40) DEFAULT NULL,
  `RDSC_INDEX` INT(11) DEFAULT NULL,
  `RDSC_TO_NODE_ID` VARCHAR(40) DEFAULT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `T_USER` (
  `ID` VARCHAR(40) NOT NULL,
  `U_NAME` VARCHAR(40) NOT NULL,
  `U_PASSWORD` VARCHAR(20) DEFAULT NULL,
  `U_IS_ACTIVE` INT(11) NOT NULL DEFAULT '0',
  `U_IS_ADMIN` INT(11) NOT NULL DEFAULT '0',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`U_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO retrieval.t_node
(ID, ND_NAME, ND_NAME_EN, ND_URI, ND_URI_NAME, ND_PARENT_ID, ND_DETAIL_TYPE_ID, ND_CONTACT) 
VALUES ('VIRTUAL_NODE', 'VIRTUAL_NODE', '', '', '', '', '', '');
